### ISSUE TITLE
add how to encrypt shell script for linux

### ISSUE THREAD

**Issue by staffnetDev** [iilegacyyii/Shellcrypt#6]

**Comment by xrombar** [comment]
my brother in christ, what ?

**Comment by staffnetDev** [comment]
hello thank you very much for answering.
I don't know much about the subject. but today I have been looking for tools to obfuscate bash script but I have not had any luck. I have exited shc but I have seen a script that reverses everything and I will open the obfuscated scripts. This tool would be good to obfuscate bash or shell as they say I don't really know.
